### ISSUE TITLE
补充几个安徽和山西的IP段

### ISSUE THREAD

**Issue by somsne** [unclemcz/ban-pcdn-ip#2]
![QQ_1721264469821](https://github.com/user-attachments/assets/bea27b7b-46d4-4d30-b684-167d02e5eacd)
36.5.81.0/24
118.81.185.0/24
只能说一颗老鼠屎苦了山西和安徽的普通用户，要被全网隔离了
![QQ_1721264855958](https://github.com/user-attachments/assets/a50e7703-d6a7-4bc7-abc7-dc82caca1b6b)

**Comment by unclemcz** [comment]
已补充，后续可以提pr哦。
